### ISSUE TITLE
Update roadmap 10/03/2022

### ISSUE THREAD

**Issue by rubensworks** [comunica/association#1]
**Core roadmap:**

_Roadmap that is relevant for all Comunica users._

- Future-oriented development: https://github.com/comunica/comunica/labels/future-oriented
    - More flexible SPARQL parser
    - ESM
    - WASM
    - Reasoning
- Improving overall performance: https://github.com/comunica/comunica/labels/performance%20%F0%9F%90%8C
    - Tweak existing join algorithms
    - Implement new join algorithms
    - Evaluating performance of upstream packages (e.g. asynciterator, graphy)
    - Bundle size
- Developer experience: https://github.com/comunica/comunica/labels/devx%20%F0%9F%8E%A8
    - Clearer error messsages
- Achieving a broader outreach
    - Transpiling to other environment (rollup, esm, dart)
- ~~Documentation~~
- ~~Alternative query languages~~

**Tangents:**

_Things that are specific to only some Comunica users._

- Different forms of query execution: https://github.com/comunica/comunica-feature-link-traversal/issues
    - Link traversal (research of Ruben T)
- Alternative query languages (GeoSPARQL?)
- Query optimization
  - Pushing down filter using the `Filterable` interface (Jacopo)

-----

@comunica/board-members I've split up the roadmap into _core_ and _tangents_ as discussed yesterday.
If there are any tangents you would like to have listed in the public roadmap, please share them here.

**Comment by rubensworks** [comment]
Pinging everyone separately, since GitHub doesn't send pings via the @comunica/board-members handle apparently...

@pietercolpaert @jeswr @jacoscaz

**Comment by jacoscaz** [comment]
Happy with how this is looking. A tangent of mine is query optimization over RDF/JS sources implementing the `Filterable` interface.

**Comment by jeswr** [comment]
Similar work to the `Filterable` interface would be https://github.com/rdfjs/N3.js/issues/281

**Comment by rubensworks** [comment]
@jacoscaz I ended up not listing your tangent separately, as I think it fits quite well in the main "performance" roadmap aspect. But happy to change if you think it still makes sense to list the tangent separately.
