### ISSUE TITLE
New bounties 10/03/2022

### ISSUE THREAD

**Issue by rubensworks** [comunica/association#2]
This is a suggestion of (some initial) issues we can place bounties on using our current [Open Collective budget](https://opencollective.com/comunica-association).

- Priority issues:
  - ~~https://github.com/comunica/comunica/issues/676 (open budget, since required effort is unknown)~~ (pause until work on asyncit and n3 is done)
  - https://github.com/comunica/comunica/issues/892 (fixed budget)
  - https://github.com/comunica/sparqlee/issues/38 (fixed budget)
- Improve overall performance:
  - https://github.com/comunica/comunica/issues/759 (fixed budget)
  - https://github.com/comunica/comunica/issues/166 (not sure about this one, as scope is rather large)
  - https://github.com/comunica/comunica/issues/971 (fixed budget)
- Developer experience:
  - https://github.com/comunica/comunica/issues/119 (open budget, since required effort is unknown)
- Achieving a broader outreach: _none for now_

@comunica/board-members Please let me know if there are any you don't agree with, or if you would like to suggest others.

**Comment by rubensworks** [comment]
Pinging everyone separately, since GitHub doesn't send pings via the @comunica/board-members handle apparently...

@pietercolpaert @jeswr @jacoscaz

**Comment by jeswr** [comment]
> https://github.com/comunica/comunica/issues/119 (open budget, since required effort is unknown)

Perhaps:
 - 1. Create a separate bounty for the `stackTrace` part of that issue
 - 2. Break it into a payment per useful `throw` statement/error message added, or do it on a per-module basis?

> https://github.com/comunica/comunica/issues/676 (open budget, since required effort is unknown)

 - I would try other parsers first to narrow down if it just a problem in the way the `ttl` parser is running.
 - Another possibility (though I need to dig further to see if this is actually the case) is that the use of something like `wrap` https://github.com/RubenVerborgh/AsyncIterator/ is causing all the data to be buffered somewhere before it is loaded into the cache? In fact is it possible that this may be resolved by https://github.com/comunica/comunica/issues/759.

The rest, LGTM @rubensworks  - as mentioned in our meeting, once these are out it might be worth trying to broaden the outreach on social media to try and attract some more devs to take them on

Even just a post saying "we've got open bounties on some issues if you want to make some extra cash" kinda thing. At a quick look some places worth posting might be:
 - https://www.reddit.com/r/typescript/
 - https://www.reddit.com/r/javascript/
 - https://www.reddit.com/r/programming/
 - https://www.reddit.com/r/coding/
 
 and then using similar hash-tags on twitter - maybe LinkedIn is worth a try too?
 
I must confess I don't actively use/have accounts for reddit/twitter so I don't know how effective it would be.

**Comment by jacoscaz** [comment]
Fixing https://github.com/comunica/comunica/issues/759 and https://github.com/RubenVerborgh/AsyncIterator/issues/44 would likely help in reducing the scope of other performance-related issues. I *think* these should be prioritized over https://github.com/comunica/sparqlee/issues/38 .

**Comment by rubensworks** [comment]
Thanks for the input!

@jacoscaz Is a bounty on https://github.com/RubenVerborgh/AsyncIterator/issues/44 still needed? I see there has been a lot of activity around that issue in the last couple of weeks.

**Comment by jacoscaz** [comment]
Indeed, the potential gains were so significant that I joined @jeswr effort and we ended up doing a great deal of work. I don't think a bounty is needed at this point but I'm obviously not against even _more_ performance improvements. However, there are probably other low-hanging fruits elsewhere that should be prioritized.

**Comment by jeswr** [comment]
Could you ping us whenever this gets listed on https://comunica.dev/association/bounties/ - I have a couple of channels with talented students that I could probably send the link to once they are up.

**Comment by rubensworks** [comment]
Yes, will do!

**Comment by rubensworks** [comment]
@pietercolpaert @jeswr @jacoscaz Bounties are up on https://comunica.dev/association/bounties/.
Unless anyone sees any issues with them, I will share them publicly on Friday.

**Comment by jeswr** [comment]
Just an observation that a couple have 'open to negotiation', while at the bottom of the page it says 'all sponsorships are based on time effort and open to negotiation'. Perhaps rephrase the first one to 'approx. depending on scope of solution' or remove the latter?


Other than that LGTM

**Comment by rubensworks** [comment]
> Just an observation that a couple have 'open to negotiation', while at the bottom of the page it says 'all sponsorships are based on time effort and open to negotiation'. Perhaps rephrase the first one to 'approx. depending on scope of solution' or remove the latter?

Good point, forgot about that. Then it might be better to just remove the 'open to negotiation' part completely.

**Comment by rubensworks** [comment]
Announced the bounties on these places:

- https://www.linkedin.com/posts/taelmanruben_comunica-a-knowledge-graph-querying-framework-activity-6925687364719669249-GWTc?utm_source=linkedin_share&utm_medium=member_desktop_web
- https://twitter.com/comunicajs/status/1519920238065852416

Didn't post to reddit, since the subreddits seem to have rules that don't allow these kinds of posts.
